################################################################################
#                               Project Manifest                               #
#                                                                              #
# This file describes the Rust project to the Cargo build tool for operations. #
################################################################################

[package]
name = "wyz"
version = "0.2.0"
authors = [
	"myrrlyn <self@myrrlyn.dev>",
]
edition = "2018"
categories = [
	"no-std",
]
description = "myrrlyn’s utility collection"
documentation = "https://docs.rs/wyz"
homepage = "https://myrrlyn.net/crates/wyz"
include = [
	"Cargo.toml",
	"src/**/*.rs",
]
keywords = [
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/myrrlyn/wyz"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[features]
alloc = []
default = ["std"]
std = ["alloc"]
mesalock_sgx = [
    "sgx_tstd",
]